# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'runLoop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BRPickerViewDemo
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'YYCache'
  pod 'FFToast'
  pod 'HMSegmentedControl'
  pod 'skpsmtpmessage'
end
